<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Authors>Song Mai Software</Authors>
    <PackageProjectUrl>https://github.com/maihcx/SYSi</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\DEV\C#DOTNET\SYSi\SYSi.BugTracker\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="D:\DEV\C#DOTNET\SYSi\SYSi.BugTracker\.editorconfig" />
  </ItemGroup>

</Project>
